name: Greeting from Mona
on: 
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '00 0 * * *'
jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@main
    - name: test my profile
      run: echo $PATH
